version: "3.5"

networks:
  dictation:
    name: dictation

services:
  dictation-core:
    image: node:lts-slim
    container_name: dictation-core
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    depends_on:
      - dictation-mongo
    ports:
      - "3001:3001"
    volumes:
      - "./core:/dictation"
      - "./start.sh:/dev.sh"
    command:
      - ./dev.sh
    networks:
      - dictation

  dictation-mongo:
    image: mongo
    container_name: dictation-mongo
    environment:
      TZ: Europe/Rome
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    ports:
      - "27017:27017"
    volumes:
      - "./docker_data/dictation-mongo:/data/db"
    networks:
      - dictation
